from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, Field


class TurnRecord(BaseModel):
    """One row in the agent_turns SQLite table.

    Written after every completed Supervisor exchange. Append-only — never
    updated or deleted. Token counts default to 0 in Stage 1c and are wired
    from result.usage() in Stage 3. The column and field are already in place.
    """

    turn_id: str = Field(description="UUID4 string, generated by the caller.")
    user_id: str
    user_email: str
    agent_name: str = Field(description="Always 'supervisor' — the entry point.")
    user_input: str
    agent_output: str = Field(description="The message delivered to the user.")
    model: str = Field(description="LLM model string from LLM_MODEL env var.")
    input_tokens: int = Field(default=0)
    output_tokens: int = Field(default=0)
    timestamp: datetime